services:
    mu_news_module.app_settings:
        class: MU\NewsModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
