services:
    # Content types
    MU\NewsModule\ContentType\ItemListType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setControllerHelper, ['@mu_news_module.controller_helper']]
            - [setModelHelper, ['@mu_news_module.model_helper']]
            - [setModulePermissionHelper, ['@mu_news_module.permission_helper']]
            - [setEntityFactory, ['@mu_news_module.entity_factory']]
            - [setCategoryDependencies, ['@mu_news_module.category_helper', '@mu_news_module.feature_activation_helper']]
        tags: ['zikula.content_type']
    MU\NewsModule\ContentType\Form\Type\ItemListType:
        parent: zikula.content_type.form.base
        arguments:
            - "@zikula_categories_module.category_repository"
        tags: ['form.type']
    MU\NewsModule\ContentType\ItemType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setControllerHelper, ['@mu_news_module.controller_helper']]
            - [setFragmentHandler, ['@fragment.handler']]
        tags: ['zikula.content_type']
    MU\NewsModule\ContentType\Form\Type\ItemType:
        parent: zikula.content_type.form.base
        arguments:
            - "@mu_news_module.entity_factory"
            - "@mu_news_module.entity_display_helper"
        tags: ['form.type']
