services:
    mu_news_module.multihook_needle.message:
        class: MU\NewsModule\Needle\MessageNeedle
        arguments:
            - '@translator.default'
            - '@router'
            - '@mu_news_module.permission_helper'
            - '@mu_news_module.entity_factory'
            - '@mu_news_module.entity_display_helper'
        tags: ['zikula.multihook_needle']
